platform: x86

cache:
  - C:\protobuf-2.6.1
  - C:\upx391w

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
  - set PROTOBUF_PREFIX=C:\protobuf-2.6.1
  - set PATH=%PROTOBUF_PREFIX%\vsprojects\Release;%PATH%
  - set PATH=C:\Qt\5.5\msvc2013\bin;%PATH%
  - set PATH=C:\upx391w;%PATH%

install:
  # Download and build libprotobuf/libprotoc/protoc, if not cached.
  - if not exist C:\protobuf-2.6.1 (
      cd C:\ &&
      curl -L -O https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.zip &&
      7z x protobuf-2.6.1.zip &&
      cd protobuf-2.6.1\vsprojects &&
      devenv protobuf.sln /Upgrade &&
      msbuild protobuf.sln /t:libprotobuf;libprotoc;protoc /p:Configuration="Release" /p:Platform="Win32" /p:BuildProjectReferences=false)

  # Download and extract UPX executable packer, if not cached.
  - if not exist C:\upx391w (
      cd C:\ &&
      curl -L -O http://upx.sourceforge.net/download/upx391w.zip &&
      7z x upx391w.zip)

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - qmake CONFIG-=debug
  - nmake zip

test_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"/examples
  - nmake /F NMakefile clean
  - nmake /F NMakefile
  - C:\MinGW\msys\1.0\bin\test -s doc/example.html
  - C:\MinGW\msys\1.0\bin\test -s doc/example.md
  - C:\MinGW\msys\1.0\bin\test -s doc/example.docbook
  - C:\MinGW\msys\1.0\bin\test -s doc/example.json

artifacts:
  path: '*.zip'
  name: protoc-gen-doc-win32-zip

deploy:
  tag: $(appveyor_repo_tag_name)
  release: protoc-gen-doc $(appveyor_repo_tag_name)
  description: 'DRAFT'
  provider: GitHub
  auth_token:
    secure: JUtSd7iVOXwTUe295uQ0AL+qf3QVGwvz04eq4avhsLWorhdND+1tIXQuq99TnFd9
  artifact: protoc-gen-doc-win32-zip
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true
