platform: x86

environment:
  PROTOBUF_PREFIX: C:\protobuf-2.6.1
  PATH: $(PROTOBUF_PREFIX)\vsprojects\Release;$(PATH)
  PATH: C:\Qt\5.5\msvc2013\bin;$(PATH)
  PATH: C:\upx391w;$(PATH)
  PATH: C:\MinGW\msys\1.0\bin;$(PATH)

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\vsvars32.bat"

install:
  # Build libprotobuf, libprotoc and protoc.
  - cd C:\
  - curl -L -O https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.zip
  - 7z x protobuf-2.6.1.zip
  - cd protobuf-2.6.1\vsprojects
  - devenv protobuf.sln /Upgrade
  - msbuild protobuf.sln /t:libprotobuf;libprotoc;protoc /p:Configuration="Release" /p:Platform="Win32" /p:BuildProjectReferences=false

  # Get UPX executable packer
  - cd C:\
  - curl -L -O http://upx.sourceforge.net/download/upx391w.zip
  - 7z x upx391w.zip

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - qmake CONFIG-=debug
  - nmake zip

test_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"/examples
  - nmake /F NMakefile clean
  - nmake /F NMakefile
  - test -s doc/example.html
  - test -s doc/example.md
  - test -s doc/example.docbook

artifacts:
  path: '*.zip'
  name: protoc-gen-doc-win32-zip

deploy:
  tag: $(appveyor_repo_tag_name)
  release: protoc-gen-doc $(appveyor_repo_tag_name)
  description: 'DRAFT'
  provider: GitHub
  auth_token:
    secure: JUtSd7iVOXwTUe295uQ0AL+qf3QVGwvz04eq4avhsLWorhdND+1tIXQuq99TnFd9
  artifact: protoc-gen-doc-win32-zip
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true
