platform: x86

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\vsvars32.bat"

install:
  # Build libprotobuf and libprotoc libraries
  - cd C:\
  - curl -L -O https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.zip
  - 7z x protobuf-2.6.1.zip
  - cd protobuf-2.6.1\vsprojects
  - devenv protobuf.sln /Upgrade
  - msbuild protobuf.sln /t:libprotobuf;libprotoc /p:Configuration="Release" /p:Platform="Win32" /p:BuildProjectReferences=false
  - set PROTOBUF_PREFIX=C:\protobuf-2.6.1

  # Get UPX executable packer
  - cd C:\
  - curl -L -O http://upx.sourceforge.net/download/upx391w.zip
  - 7z x upx391w.zip
  - set PATH=C:\upx391w;%PATH%

build_script:
  - C:\Qt\5.5\msvc2013\bin\qmake CONFIG-=debug CONFIG+=release
  - nmake zip

deploy:
  release: protoc-gen-doc %APPVEYOR_REPO_TAG_NAME%
  description: 'TODO: Update this'
  provider: GitHub
  auth_token:
    secure: JUtSd7iVOXwTUe295uQ0AL+qf3QVGwvz04eq4avhsLWorhdND+1tIXQuq99TnFd9
  artifact: /.*\.zip/
  draft: true
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
