dist: trusty
sudo: required

language: cpp

compiler:
 - gcc
 - clang

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libqt5core5a qt5-qmake qt5-default
 - sudo apt-get install -qq libprotobuf-dev libprotoc-dev protobuf-compiler
 - sudo apt-get install -qq docbook-xsl fop libservlet2.4-java

before_script:
 - export DOCBOOK_XSL=/usr/share/xml/docbook/stylesheet/docbook-xsl/fo/docbook.xsl
 - export QMAKESPEC=linux-$([[ $CXX = "g++" ]] && echo "g++" || echo "clang")

script:
 - qmake
 - make
 - cd examples
 - make clean
 - make
 - test -s doc/example.html
 - test -s doc/example.md
 - test -s doc/example.docbook
 - test -s doc/example.pdf
