language: cpp

addons:
 apt:
  packages:
   - libqt5core5a
   - qt5-qmake
   - qt5-default
   - libprotobuf-dev
   - libprotoc-dev
   - protobuf-compiler
   - docbook-xsl
   - fop
   - libservlet2.4-java

matrix:
 include:
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
  - os: linux
    dist: trusty
    sudo: required
    compiler: clang

before_script:
 - export DOCBOOK_XSL=/usr/share/xml/docbook/stylesheet/docbook-xsl/fo/docbook.xsl
 - export QMAKESPEC=linux-$([[ $CXX = "g++" ]] && echo "g++" || echo "clang")

script:
 - qmake
 - make
 - cd examples
 - make clean
 - make
 - test -s doc/example.html
 - test -s doc/example.md
 - test -s doc/example.docbook
 - test -s doc/example.pdf
